---
- name: irq_tune | Checkout irq-tune remote git repo
  git:
    repo: "{{ vars['irq_tune_repo'] }}"
    dest: "/tmp/irq-tune"
- name: irq_tune | Make irq-tune directory
  file:
    path: "{{ hostvars[inventory_hostname]['irq_tune_dest'] }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
- name: irq_tune | Deploy irq-tune
  copy:
    src: "/tmp/irq-tune/irq-tune.py"
    remote_src: "yes"
    dest: "{{ hostvars[inventory_hostname]['irq_tune_exec'] }}"
    mode: "0755"
    owner: "root"
    group: "root"
    force: "yes"
    validate: "%s --help"
- name: irq_tune | Delete irq-tune local git repo
  file:
    name: "/tmp/irq-tune"
    state: "absent"
  diff: "false"
