---
- name: Add the OS specific variables
  include_vars: "{{ hostvars[inventory_hostname]['ansible_os_family'] + '.yml' }}"
- name: Checkout irq-tune remote git repo
  git:
    repo: "{{ irq_tune_repo }}"
    dest: "/tmp/irq-tune"
  register: "irq_tune_git"
- name: Make work directories
  file:
    path: "{{ hostvars[inventory_hostname]['irq_tune_dest'] }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  register: "irq_tune_dir"
  when: "irq_tune_git|success"
- name: Deploy irq-tune
  copy:
    src: "/tmp/irq-tune/irq-tune.py"
    remote_src: True
    dest: {{ hostvars[inventory_hostname]['irq_tune_exec'] }}"
    mode: "0755"
    owner: "root"
    group: "root"
    force: "yes"
    validate: "%s --help"
  register: "irq_tune_deploy"
- name: Delete irq-tune local git repo
  file:
    name: "/tmp/irq-tune"
    state: "absent"
- name: Deploy irq-tune json
  template:
    src: "irq.j2"
    dest: "{{ hostvars[inventory_hostname]['irq_tune_dest'] + '/' + 'irq.json' }}"
    group: "root"
    owner: "root"
    mode: "0644"
    force: "yes"
  when: "hostvars[inventory_hostname]['irq_tune'] is defined and (irq_tune_deploy|success and irq_tune_dir|success)"
